#!/bin/bash
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2018 Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
# Copyright (C) 2022 Frédéric Pierret (fepitre) <frederic@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Clamp the topmost changelog entry date ("Build for ...") to the previous one
# (actual meaningful entry)
#Reverted clamp-changelog-entry-date

CHANGELOG_PATH="$1"

if [ ! -r "$CHANGELOG_PATH" ]; then
    echo "Changelog file '$CHANGELOG_PATH' inaccessible!" >&2
    exit 1
fi

# Get previous date from the changelog
PREVIOUS_DATE=$(grep '^ --' "$CHANGELOG_PATH" | head -n 2 | tail -n 1 | grep -o '  .*')

# Use SOURCE_DATE_EPOCH if available; otherwise, use PREVIOUS_DATE
CURRENT_DATE=$(date -u -d "@${SOURCE_DATE_EPOCH:-$PREVIOUS_DATE}" +"%Y-%m-%d %H:%M:%S")

# Replace the topmost date with CURRENT_DATE
sed -e "0,/^ --/s/^\( --.*\)\(  .*\)/\1$CURRENT_DATE/" -i "$CHANGELOG_PATH"
touch --date="$CURRENT_DATE" "$CHANGELOG_PATH"
